### ISSUE TITLE
Store Location Latitude and Longitude is required 

### ISSUE THREAD

**Issue by pingyangtiaer** [sofyansitorus/WooCommerce-Shipping-Distance-Matrix#1] opened 2018-01-28 23:19 UTC
I added you plugin in word press, I also got an api key from google. the map showed 1 second then I got the error:
Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details. 
Actually the address is already set for the woocommerce plugin.
Do you have any idea for what is going on?
Looking forward to hearing from you.
Peter

**Comment by sofyansitorus** [comment] 2018-01-29 18:34
Hi,

Thank you for using my plugin.

Based on the error stated by google Maps API, probably the issue caused by the API Key is incorrect. Try to open your browser console log before load the settings page, the cause of error will be printed there.

Follow link below for how to open browser console log for debugging.

https://developers.google.com/web/tools/chrome-devtools/console/

**Comment by sofyansitorus** [comment] 2018-01-30 02:39
Hi, There was I put a link in the setting panel to linked to Google API Console. Click the get the API Key. There should be no problem either you install the plugin thru WordPress or upload it manually.

**Comment by sofyansitorus** [comment] 2018-01-30 05:29
Anyway, you need to enable API and service for these 3: 

1. Google Maps JavaScript API
2. Google Maps Geocoding API
3. Google Maps Distance Matrix API

**Comment by sofyansitorus** [comment] 2018-02-02 01:34
This issue is fixed in release 1.2.7

**Closed** 2018-02-02 01:33 UTC
